### ISSUE TITLE
Icon for archive plugin

### ISSUE THREAD

**Issue by arobase13** [beliys/harry#1]
Hello, great your skin for Roundcube, the offer of skin for Roundcube is unfortunately very weak, I love your skin.
Just a question, I realize that the skin does not provide icon for the plugin archive, do you plan to upgrade the skin as for example the addition of icon for other plugins as an archive for example.
Anyway excellent work, thank you again.

**Comment by bilkoua** [comment]
Hi, please save as html page where have missing icons, make screenshot and share for me. I try help you.

**Comment by arobase13** [comment]
Good evening, thank you for your answer.

Here is the link to [download](http://www.sendbox.fr/e50e3bb14f5d96a9/mail.pookiemia.fr_Webmail___Bo%C3%AEte_de_r%C3%A9ception.htm) the html page.
Please note that the interface is in French.
For info I use mailinabox.

**Comment by bilkoua** [comment]
You don't make screenshot with missed icon...

**Comment by arobase13** [comment]
[Screenshot](http://img15.hostingpics.net/pics/397041screen.png)

**Comment by bilkoua** [comment]
Please update skin and check...

**Comment by arobase13** [comment]
Ok, I did:

> git clone https://github.com/beliys/harry /tmp/harry
> cp -rf /tmp/harry/skins/harry /usr/local/lib/roundcubemail/skins/harry
> cp -rf /tmp/harry/plugins/* /usr/local/lib/roundcubemail/plugins
> chown -R www-data:www-data /usr/local/lib/roundcubemail
> rm -rf /tmp/harry

Always the same, I delete the skin and I reinstall?

After taking a look in the skin folder, there is a folder for markasjunk2, but not for archive, this must explain the problem

**Comment by bilkoua** [comment]
Possible reinstall without delete. You can look last commit and look than icons for markasjunk2 and archive setting in styles.min.css as in larry skin (harry based on him) Please, try clear cache in browser

**Comment by arobase13** [comment]
Sorry, I did not understand what I had to do.

**Comment by bilkoua** [comment]
Do you have icon after update? I install this plugin and have icon on test server - [Screenshot](http://imgur.com/a/rqPrU)

**Comment by arobase13** [comment]
Not knowing how to do the update I did directly a reinstallation not always no icon

**Comment by bilkoua** [comment]
You can update manually looking last commit - [https://github.com/beliys/harry/commit/4392efd94b7a68614a090a3bbc9fac486dada074](https://github.com/beliys/harry/commit/4392efd94b7a68614a090a3bbc9fac486dada074)
if manually change css file dont help, than i need debug problem for help ( you can make test account and send access to him on my mail )

**Comment by arobase13** [comment]
Super, awesome, great, it works, the icon is finally visible.
I want to thank you for your help, and also want to encourage you, your skin is great, I hope you will continue.
thanks again
