### ISSUE TITLE
the answering machine and filters are not functional

### ISSUE THREAD

**Issue by arobase13** [beliys/harry#2]
Hello, just to point out a problem, in the setting of roundcube with the skin Harry, in the menu on the left, the answering machine and filters are not functional.

I attach a screen + html page

thank you in advance

Manu

[https://mon-partage.fr/f/H4qEhHPY/](url) and [https://mon-partage.fr/f/psOaqz8b/](url)

**Comment by bilkoua** [comment]
Hi, pls update and check...
https://github.com/beliys/harry/commit/f93e681fe925a8d7ab3fe55de6a72de8908fbf13

**Comment by arobase13** [comment]
FICHER INTROUVABLE
La ressource demandée n'a pas été trouvée !
Veuillez contacter l'administrateur de votre serveur.

Échec de la demande:
//mail.pookiemia.fr/mail/?_task=settings&_action=plugin.managesieve

**Comment by bilkoua** [comment]
skin only change style... problem with plugin. Is him work on larry skin?

**Comment by arobase13** [comment]
With the Larry skin it works but displays this error message

Managesieve: No sieve scripts found (This can be ignored on first run)

**Comment by arobase13** [comment]
With the classic theme the plugin works

**Comment by bilkoua** [comment]
u can try copy larry skin folder for plugin to harry... Its can be help...

**Comment by arobase13** [comment]
In plugin and larry I have copied the folder of the plugin managesieve in plugin harry, it's ok, but still the error message. Managesieve: No sieve scripts found (This can be ignored on first run)

**Comment by arobase13** [comment]
No luck I just noticed that autoresponder and filter displays a blank page, I managed to make it work again, but continuous filter to return a blank page ....

**Comment by arobase13** [comment]
Well, I fixed the problems I encountered, but I still have this error

> Managesieve: No sieve scripts found (This can be ignored on first run)

But it happens on all skins, have you an idea of where I have to look?

**Comment by bilkoua** [comment]
I think be better if you contact with plugin developers.

**Comment by arobase13** [comment]
I just posted on the github of mailinabox, I would post below the solution.
