### ISSUE TITLE
Invisible central part

### ISSUE THREAD

**Issue by arobase13** [beliys/harry#4]
hello, I just installed your skin on the Roundcube version 1.3.7, but a part is missed, as in the image visible on the link below.

The skins seems to be compatible if I click on about for version 1.3.6.

Would the skins become incompatible? That would be a pity.

Good evening and good weekend

[http://image.noelshack.com/fichiers/2018/38/6/1537633822-roudcubeharry.png](url)

**Comment by bilkoua** [comment]
Try to update to last version. Now skin support 1.3.7 and now skin re-create with `"extends": "larry"` for better compatibility and more simple update.
