### ISSUE TITLE
some docs to how to change colorized theme to green, black white etc

### ISSUE THREAD

**Issue by mckaygerhard** [beliys/harry#5]
hi, as i posted in forum great theme, so,  some docs to how to change colorized theme to green, black white etc?¡?

**Comment by bilkoua** [comment]
Hi, when it comes to Roundcube themes, any high-quality coloring should be done manually using the developer's tools in the browser to find the style of a particular element and change its color. In simple cases, it is possible to help auto-replacement of the main colors with subsequent correction.

**Comment by mckaygerhard** [comment]
umm tried some coding yesterday but was not so easy .. well i try to made some work and post feedback here..
