### ISSUE TITLE
roundcube 1.4

### ISSUE THREAD

**Issue by dia-de-muertos** [beliys/harry#6]
Hi,
harry 0.3.1 seems not to work with roundcube 1.4.11
It looks exactly like larry skin.
As I prefer harry over all other skins,
are there any plans to get it work with roundcube 1.4?

**Comment by bilkoua** [comment]
Hi, unfortunately I don't use webmail now, including roundcube and I can't keep track of the skin relevance. Thanks for the issue. Try updating.

**Comment by dia-de-muertos** [comment]
Hello,
harry works again, GREAT!
Thanks for your fast help.
